# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules =
    [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/iso" = {
    device = "/dev/disk/by-uuid/1980-01-01-00-00-00-00";
    fsType = "iso9660";
  };

  fileSystems."/nix/.ro-store" = {
    device = "/iso/nix-store.squashfs";
    fsType = "squashfs";
    options = [ "loop" ];
  };

  fileSystems."/nix/.rw-store" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/nix/store" = {
    device = "overlay";
    fsType = "overlay";
  };

  fileSystems."/nix/store" = {
    device = "/nix/store";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/mnt" = {
    device = "/dev/disk/by-uuid/a8b2a28a-6318-4786-8018-c0abd3b5c09c";
    fsType = "ext4";
  };

  fileSystems."/mnt/boot" = {
    device = "/dev/disk/by-uuid/09E4-767A";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/0b421f38-af79-49af-a111-31ed002255d3"; }];
}
