name: fb
parent: default

matches:
  - trigger: "//1"
    replace: "1 on 1"
  - trigger: "//an"
    replace: "Android"
  - trigger: "//be"
    replace: "Better Engineering"
  - trigger: "//ch"
    replace: "Core Health"
  - trigger: "//cf"
    replace: "Client Foundation"
  - trigger: "//cp"
    replace: "Core Health Prevention"
  - trigger: "//ee"
    replace: "Exceeds Expectations"
  - trigger: "//fb"
    replace: "Facebook"
  - trigger: "//ge"
    replace: "Greatly Exceeds"
  - trigger: "//rl"
    replace: "Reality Labs"
  - trigger: "//fs"
    replace: "Fast & Safe"
  - trigger: "//hc"
    replace: "Health Compass"
  - trigger: "//ig"
    replace: "Instagram"
  - trigger: "//io"
    replace: "iOS"
  - trigger: "//it"
    replace: "Incident Tracker"
  - trigger: "//ma"
    replace: "Meets All"
  - trigger: "//ml"
    replace: "MobileLab"
  - trigger: "//msg"
    replace: "Messenger"
  - trigger: "//pe"
    replace: "performance"
  - trigger: "//pi"
    replace: "Project Impact"
  - trigger: "//ppi"
    replace: "Privacy Product Infrastructure"
  - trigger: "//pai"
    replace: "Privacy Aware Infrastructure"
  - trigger: "//pdt"
    replace: "Privacy Data Transparency"
  - trigger: "//sz"
    replace: "Sapienz"
  - trigger: "//tv"
    replace: "Testing & Verification"
  - trigger: "//ul"
    replace: "UltraLab"
  - trigger: "//upv"
    replace: "Unified Prevention View"
  - trigger: "//vd"
    replace: "virtual device"
  - trigger: "//wa"
    replace: "WhatsApp"
