name: fb
parent: default

matches:
  - trigger: "/11"
    replace: "1 on 1"
  - trigger: "/an"
    replace: "Android"
  - trigger: "/be"
    replace: "Better Engineering"
  - trigger: "/ch"
    replace: "Core Health"
  - trigger: "/cf"
    replace: "Client Foundation"
  - trigger: "/cp"
    replace: "Core Health Prevention"
  - trigger: "/fb"
    replace: "Facebook"
  - trigger: "/fs"
    replace: "Fast & Safe"
  - trigger: "/hc"
    replace: "Health Compass"
  - trigger: "/ig"
    replace: "Instagram"
  - trigger: "/io"
    replace: "iOS"
  - trigger: "/ml"
    replace: "MobileLab"
  - trigger: "/mp"
    replace: "Mobile Profilers"
  - trigger: "/msg"
    replace: "Messenger"
  - trigger: "/pe"
    replace: "performance"
  - trigger: "/pd"
    replace: "physical device"
  - trigger: "/tv"
    replace: "Testing & Verification"
  - trigger: "/upv"
    replace: "Unified Prevention View"
  - trigger: "/vd"
    replace: "virtual device"
  - trigger: "/wa"
    replace: "WhatsApp"
